<a href="https://colab.research.google.com/github/liyaemil123/python-project/blob/main/pandas/student_performance_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Student Performance Analysis**

# **OBJECTIVE**

The objective of this projects is to analyze student performance and study habits using Python, Pandas, and NumPy. The project aims to identify relationships between factors such as study hours, attendance, assignment completion, and academic marks. By analyzing the data, the project seeks to identify patterns that may influence students' academic performance and provide meaningful insights into the factors associated with better learning outcomes.

# **Problem Definition**

Student academic performance can be influenced by several factors such as study hours, attendance, assignment completion, sleep patterns, and previous academic performance. However, it can be difficult to understand which factors have the greatest impact on students' final marks when looking at individual records.

This project aims to analyze student performance data using Python, Pandas, and NumPy to identify patterns and relationships between students' study habits, attendance, assignment completion, sleep hours, previous semester marks, and final marks. By analyzing and comparing these factors, the project seeks to understand the factors associated with better academic performance and identify areas that may help students improve their learning outcomes.

**1. DATA LOADING**

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_performance.csv")

df

,Student_ID,Age,Gender,Study_Hours_Per_Day,Attendance_Percentage,Assignments_Completed,Sleep_Hours_Per_Day,Previous_Semester_Marks,Final_Marks,Grade
0,1001,20,Male,2.3,89.9,5,8.4,48.7,52.1,D
1,1002,21,Male,7.2,86.0,5,5.1,72.7,76.1,B
2,1003,19,Male,4.8,94.0,4,8.3,93.5,81.4,A
3,1004,21,Male,6.7,86.3,10,6.1,71.2,81.8,A
4,1005,21,Male,7.3,82.7,5,5.5,76.5,67.1,C
...,...,...,...,...,...,...,...,...,...,...
95,1096,20,Male,5.6,61.0,6,8.9,84.2,68.7,C
96,1097,20,Female,2.6,98.5,10,5.2,64.8,65.7,C
97,1098,21,Female,6.0,93.4,4,8.6,76.1,79.5,B
98,1099,17,Female,2.7,87.8,5,7.1,88.1,65.0,C
99,1100,21,Female,3.3,76.4,8,9.0,92.5,74.0,B

**2.Initial Overview**

In [7]:
# shape()
# Show Number of rows and columns

df.shape

(100, 10)

In [10]:
# info()
# Check column names and data types.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               100 non-null    int64
 1   Age                      100 non-null    int64
 2   Gender                   100 non-null    object
 3   Study_Hours_Per_Day      100 non-null    float64
 4   Attendance_Percentage    100 non-null    float64
 5   Assignments_Completed    100 non-null    int64
 6   Sleep_Hours_Per_Day      100 non-null    float64
 7   Previous_Semester_Marks  100 non-null    float64
 8   Final_Marks              100 non-null    float64
 9   Grade                    100 non-null    object
dtypes: float64(5), int64(3), object(2)
memory usage: 7.9+ KB

In [12]:
# describe()
# Get statistical information.

df.describe()

,Student_ID,Age,Study_Hours_Per_Day,Attendance_Percentage,Assignments_Completed,Sleep_Hours_Per_Day,Previous_Semester_Marks,Final_Marks
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,1050.500000,19.690000,4.352000,81.536000,6.91000,7.116000,73.244000,70.518000
std,29.011492,1.624901,2.046751,11.587328,1.92325,1.274198,14.483472,9.182244
min,1001.000000,17.000000,1.000000,60.600000,4.00000,5.000000,45.700000,52.100000
25%,1025.750000,18.000000,2.675000,72.475000,5.00000,6.100000,62.850000,64.500000
50%,1050.500000,20.000000,4.500000,82.500000,7.00000,7.200000,74.350000,69.000000
75%,1075.250000,21.000000,5.925000,91.800000,8.00000,8.225000,86.300000,75.800000
max,1100.000000,22.000000,7.900000,99.600000,10.00000,9.000000,95.000000,96.600000

2. **HEAD**
 - Shows the first 5 students.

In [4]:
df.head()

,Student_ID,Age,Gender,Study_Hours_Per_Day,Attendance_Percentage,Assignments_Completed,Sleep_Hours_Per_Day,Previous_Semester_Marks,Final_Marks,Grade
0,1001,20,Male,2.3,89.9,5,8.4,48.7,52.1,D
1,1002,21,Male,7.2,86.0,5,5.1,72.7,76.1,B
2,1003,19,Male,4.8,94.0,4,8.3,93.5,81.4,A
3,1004,21,Male,6.7,86.3,10,6.1,71.2,81.8,A
4,1005,21,Male,7.3,82.7,5,5.5,76.5,67.1,C